FROM mcr.microsoft.com/devcontainers/python:3.12-bookworm

WORKDIR /app

# install ngspice
RUN apt-get update && \
    sudo apt-get -y install ngspice && \
    rm -rf /var/lib/apt/lists/*

# intstall my Python modules
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
