# Top-level settings (common to all projects)
[global]
ngspice_exe_str = "/usr/bin/ngspice"

# Section 1-04-04 Linear Regulator
[sec_1_04_04]
proj_path_str = "/workspaces/sw_pwr_book_sim/circuits/sec_1_04_04_lin_reg"
