# Top-level settings (common to all projects)
[global]
ngspice_exe_str = "/usr/bin/ngspice"
netlists_dir_str = "netlists"        # relative to proj dir, where netlists will be stored
results_dir_str = "sim_results"      # rel to proj dir, where sim results will be stored

# Section 1-04-02 Linear Regulator
[sec_1_04_02]
proj_path_str = "/workspaces/sw_pwr_book_sim/circuits/sec_1_04_02_lin_reg"
description = "From power supply book: section 1.04.02 linear regulator"

# Section 1-04-04 Linear Regulator
[sec_1_04_04]
proj_path_str = "/workspaces/sw_pwr_book_sim/circuits/sec_1_04_04_lin_reg"
description = "From power supply book: section 1.04.04 linear regulator"
